function G = originGravityVector(theta0,theta1,m,g,L,D)
%ORIGINGRAVITYVECTOR
%    G = ORIGINGRAVITYVECTOR(THETA0,THETA1,M,G,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Feb-2022 16:43:44

t2 = theta0+theta1;
t3 = theta0.^2;
t4 = 1.0./theta1;
t7 = sqrt(pi);
t9 = 1.0./sqrt(theta1);
t5 = t4.^2;
t6 = t2.^2;
t8 = 1.0./t7;
t10 = t9.^5;
t11 = sqrt(t4);
t13 = (t3.*t4)./2.0;
t12 = 1.0./t11;
t14 = cos(t13);
t15 = sin(t13);
t16 = (t4.*t6)./2.0;
t19 = t8.*t9.*theta0;
t22 = t2.*t8.*t9;
t17 = cos(t16);
t18 = sin(t16);
t20 = fresnelc(t19);
t21 = fresnels(t19);
t23 = fresnelc(t22);
t24 = fresnels(t22);
t25 = -t20;
t26 = -t21;
G = [L.*g.*m.*t9.*t11.*t14.*(t14-t17).*(-1.0./2.0)-(L.*g.*m.*t9.*t11.*t15.*(t15-t18))./2.0+(L.*g.*m.*t7.*1.0./t12.^3.*t15.*theta0.*(t20-t23))./2.0-(L.*g.*m.*t7.*1.0./t12.^3.*t14.*theta0.*(t21-t24))./2.0;(L.*g.*m.*t10.*t12.*t14.*(t14.*theta0-t17.*theta0+t17.*theta1))./4.0+(L.*g.*m.*t10.*t12.*t15.*(t15.*theta0-t18.*theta0+t18.*theta1))./4.0+(L.*g.*m.*t7.*1.0./t12.^3.*t14.*(t20-t23))./4.0+(L.*g.*m.*t7.*1.0./t12.^3.*t15.*(t21-t24))./4.0-(L.*g.*m.*t3.*t7.*1.0./t12.^5.*t15.*(t20-t23))./4.0+(L.*g.*m.*t3.*t7.*1.0./t12.^5.*t14.*(t21-t24))./4.0];
