function G = originGravityVector(theta0,theta1,m,g,L,D)
%ORIGINGRAVITYVECTOR
%    G = ORIGINGRAVITYVECTOR(THETA0,THETA1,M,G,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Feb-2022 09:54:50

t2 = theta0+theta1;
t3 = theta0.^2;
t4 = 1.0./theta1;
t7 = sqrt(pi);
t5 = t4.^2;
t6 = t2.^2;
t8 = 1.0./t7;
t9 = sqrt(t4);
t11 = (t3.*t4)./2.0;
t10 = 1.0./t9;
t12 = cos(t11);
t13 = sin(t11);
t14 = (t4.*t6)./2.0;
t17 = t8.*t9.*theta0;
t20 = t2.*t8.*t9;
t15 = cos(t14);
t16 = sin(t14);
t18 = fresnelc(t17);
t19 = fresnels(t17);
t21 = fresnelc(t20);
t22 = fresnels(t20);
t23 = -t21;
t24 = -t22;
t25 = t18+t23;
t26 = t19+t24;
G = [-L.*g.*m.*t7.*t9.*t12.*(t8.*t9.*t12-t8.*t9.*t15)-L.*g.*m.*t7.*t9.*t13.*(t8.*t9.*t13-t8.*t9.*t16)-L.*g.*m.*t7.*1.0./t10.^3.*t12.*t26.*theta0+L.*g.*m.*t7.*1.0./t10.^3.*t13.*t25.*theta0;(L.*g.*m.*t5.*t12.*(t12.*theta0-t15.*theta0+t15.*theta1))./2.0+(L.*g.*m.*t5.*t13.*(t13.*theta0-t16.*theta0+t16.*theta1))./2.0+(L.*g.*m.*t7.*1.0./t10.^3.*t12.*t25)./2.0+(L.*g.*m.*t7.*1.0./t10.^3.*t13.*t26)./2.0+(L.*g.*m.*t3.*t7.*1.0./t10.^5.*t12.*t26)./2.0-(L.*g.*m.*t3.*t7.*1.0./t10.^5.*t13.*t25)./2.0];
