function D = originDampingMatrix(beta)
%ORIGINDAMPINGMATRIX
%    D = ORIGINDAMPINGMATRIX(BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Feb-2022 14:33:13

t2 = beta./2.0;
D = reshape([beta,t2,t2,beta./3.0],[2,2]);
