function D = originDampingMatrix(beta)
%ORIGINDAMPINGMATRIX
%    D = ORIGINDAMPINGMATRIX(BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Feb-2022 16:43:45

t2 = beta./2.0;
D = reshape([beta,t2,t2,beta./3.0],[2,2]);
