function K = originElasticMatrix(k)
%ORIGINELASTICMATRIX
%    K = ORIGINELASTICMATRIX(K)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Feb-2022 09:54:50

t2 = k./2.0;
K = reshape([k,t2,t2,k./3.0],[2,2]);
