function C_lin = C_lin(theta_r,theta0,theta1,L)
%C_lin
%    C_lin = C_lin(THETA_R,THETA0,THETA1,L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Mar-2022 11:14:23

t2 = theta0.^2;
t3 = theta1.^2;
t4 = theta0.*theta1.*2.0;
t5 = theta1.*theta_r.*2.0;
t6 = 1.0./theta1;
t8 = sqrt(pi);
t7 = 1.0./t3;
t9 = -t2;
t10 = t6.*theta0;
t11 = t6.*theta_r;
t12 = 1.0./t8;
t14 = sqrt(t6);
t18 = (t2.*t6)./2.0;
t19 = t2+t3+t4;
t24 = t6.*(t2-t5).*(-1.0./2.0);
t13 = t10+1.0;
t15 = -t11;
t16 = 1.0./t14;
t20 = t5+t9;
t21 = t12.*t14.*theta0;
t25 = t7.*(t2-t5).*(-1.0./2.0);
t26 = (t6.*t19)./2.0;
t27 = cos(t24);
t28 = sin(t24);
t36 = t18+t24;
t17 = t16.^3;
t22 = fresnelc(t21);
t23 = fresnels(t21);
t29 = t7.*t12.*t16.*theta0;
t31 = t12.*t13.*t16;
t34 = t15+t25;
t37 = cos(t36);
t38 = sin(t36);
t39 = t24+t26;
t30 = -t29;
t32 = fresnelc(t31);
t33 = fresnels(t31);
t35 = (t7.*t12.*t13.*t17)./2.0;
t40 = cos(t39);
t41 = sin(t39);
t42 = t30+t35;
mt1 = [L.*t8.*t14.*t22.*t27-L.*t8.*t14.*t23.*t28-L.*t8.*t14.*t27.*t32+L.*t8.*t14.*t28.*t33,L.*t8.*t14.*t22.*t28+L.*t8.*t14.*t23.*t27-L.*t8.*t14.*t27.*t33-L.*t8.*t14.*t28.*t32,L.*t6.*t38-L.*t6.*t41-(L.*t8.*t22.*t27.*theta0)./t17+(L.*t8.*t23.*t28.*theta0)./t17+(L.*t8.*t27.*t32.*theta0)./t17-(L.*t8.*t28.*t33.*theta0)./t17,-L.*t6.*t37+L.*t6.*t40-(L.*t8.*t22.*t28.*theta0)./t17-(L.*t8.*t23.*t27.*theta0)./t17+(L.*t8.*t27.*t33.*theta0)./t17+(L.*t8.*t28.*t32.*theta0)./t17];
mt2 = [L.*t7.*t38.*theta0.*(-1.0./2.0)+L.*t8.*t14.*t41.*(t29-t35)+L.*t8.*t14.*t22.*t27.*(t11+(t7.*(t2-t5))./2.0)-L.*t8.*t14.*t23.*t28.*(t11+(t7.*(t2-t5))./2.0)-L.*t8.*t14.*t27.*t32.*(t11+(t7.*(t2-t5))./2.0)+L.*t8.*t14.*t28.*t33.*(t11+(t7.*(t2-t5))./2.0)-(L.*t7.*t8.*t16.*t22.*t28)./2.0-(L.*t7.*t8.*t16.*t23.*t27)./2.0+(L.*t7.*t8.*t16.*t27.*t33)./2.0+(L.*t7.*t8.*t16.*t28.*t32)./2.0];
mt3 = [(L.*t7.*t37.*theta0)./2.0-L.*t8.*t14.*t40.*(t29-t35)+L.*t8.*t14.*t22.*t28.*(t11+(t7.*(t2-t5))./2.0)+L.*t8.*t14.*t23.*t27.*(t11+(t7.*(t2-t5))./2.0)-L.*t8.*t14.*t27.*t33.*(t11+(t7.*(t2-t5))./2.0)-L.*t8.*t14.*t28.*t32.*(t11+(t7.*(t2-t5))./2.0)+(L.*t7.*t8.*t16.*t22.*t27)./2.0-(L.*t7.*t8.*t16.*t23.*t28)./2.0-(L.*t7.*t8.*t16.*t27.*t32)./2.0+(L.*t7.*t8.*t16.*t28.*t33)./2.0];
C_lin = reshape([mt1,mt2,mt3],2,3);
