function D = dampingMatrix(beta)
%DAMPINGMATRIX
%    D = DAMPINGMATRIX(BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Feb-2022 11:11:44

t2 = beta./2.0;
D = reshape([0.0,0.0,0.0,0.0,beta,t2,0.0,t2,beta./3.0],[3,3]);
