function K = elasticMatrix(k)
%ELASTICMATRIX
%    K = ELASTICMATRIX(K)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Feb-2022 11:11:44

t2 = k./2.0;
K = reshape([0.0,0.0,0.0,0.0,k,t2,0.0,t2,k./3.0],[3,3]);
