function G = gravityVector(theta_r,theta0,theta1,m,g,L,D)
%GRAVITYVECTOR
%    G = GRAVITYVECTOR(THETA_R,THETA0,THETA1,M,G,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Feb-2022 11:11:43

t2 = theta0+theta1;
t3 = theta0.^2;
t4 = theta1.*theta_r.*2.0;
t5 = 1.0./theta1;
t7 = sqrt(pi);
t8 = sqrt(theta1);
t6 = t5.^2;
t9 = -t3;
t10 = t5.*theta_r;
t11 = 1.0./t7;
t12 = 1.0./t8;
t14 = sqrt(t5);
t24 = t5.*(t3-t4).*(-1.0./2.0);
t13 = t12.^3;
t15 = -t10;
t16 = 1.0./t14;
t17 = t4+t9;
t18 = t11.*t12.*theta0;
t21 = t2.*t11.*t12;
t25 = t6.*(t3-t4).*(-1.0./2.0);
t26 = cos(t24);
t27 = sin(t24);
t19 = fresnelc_approx(t18);
t20 = fresnels_approx(t18);
t22 = fresnelc_approx(t21);
t23 = fresnels_approx(t21);
t28 = t15+t25;
et1 = (L.*g.*m.*t13.*t14.*theta0.*cos(t24+(t3.*t5)./2.0))./4.0+(L.*g.*m.*t7.*1.0./t16.^3.*t19.*t26)./4.0-(L.*g.*m.*t7.*1.0./t16.^3.*t20.*t27)./4.0-(L.*g.*m.*t7.*1.0./t16.^3.*t22.*t26)./4.0+(L.*g.*m.*t7.*1.0./t16.^3.*t23.*t27)./4.0+(L.*g.*m.*t7.*t14.*cos(t24+(t5.*(t3+theta0.*theta1.*2.0+1.0./t6))./2.0).*(t11.*t12-(t2.*t11.*t13)./2.0))./2.0+(L.*g.*m.*t7.*t14.*t19.*t27.*(t10+(t6.*(t3-t4))./2.0))./2.0+(L.*g.*m.*t7.*t14.*t20.*t26.*(t10+(t6.*(t3-t4))./2.0))./2.0-(L.*g.*m.*t7.*t14.*t22.*t27.*(t10+(t6.*(t3-t4))./2.0))./2.0;
et2 = L.*g.*m.*t7.*t14.*t23.*t26.*(t10+(t6.*(t3-t4))./2.0).*(-1.0./2.0);
G = [(L.*g.*m.*t7.*t14.*t19.*t27)./2.0+(L.*g.*m.*t7.*t14.*t20.*t26)./2.0-(L.*g.*m.*t7.*t14.*t22.*t27)./2.0-(L.*g.*m.*t7.*t14.*t23.*t26)./2.0;(t13.*t14.*(L.*g.*m.*theta1.*cos(theta0+theta1./2.0+theta_r)-L.*g.*m.*theta1.*cos(theta_r)-L.*g.*m.*t7.*t8.*t19.*t27.*theta0-L.*g.*m.*t7.*t8.*t20.*t26.*theta0+L.*g.*m.*t7.*t8.*t22.*t27.*theta0+L.*g.*m.*t7.*t8.*t23.*t26.*theta0))./2.0;et1+et2];
