function G = gravityVector(theta_r,theta0,theta1,m,g,L,D)
%GRAVITYVECTOR
%    G = GRAVITYVECTOR(THETA_R,THETA0,THETA1,M,G,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Feb-2022 22:47:15

t2 = theta0+theta1;
t3 = theta0.^2;
t4 = theta1.*theta_r.*2.0;
t5 = 1.0./theta1;
t8 = sqrt(pi);
t12 = 1.0./sqrt(theta1);
t6 = t5.^2;
t7 = t2.^2;
t9 = -t3;
t10 = t5.*theta_r;
t11 = 1.0./t8;
t13 = t12.^3;
t14 = sqrt(t5);
t17 = (t3.*t5)./2.0;
t31 = t5.*(t3-t4).*(-1.0./2.0);
t15 = -t10;
t16 = 1.0./t14;
t18 = t4+t9;
t19 = cos(t17);
t20 = sin(t17);
t21 = (t5.*t7)./2.0;
t22 = t11.*t12;
t32 = t6.*(t3-t4).*(-1.0./2.0);
t33 = (t2.*t11.*t13)./2.0;
t35 = cos(t31);
t36 = sin(t31);
t23 = cos(t21);
t24 = sin(t21);
t25 = t22.*theta0;
t28 = t2.*t22;
t34 = -t33;
t37 = t15+t32;
t26 = fresnelc_approx(t25);
t27 = fresnels_approx(t25);
t29 = fresnelc_approx(t28);
t30 = fresnels_approx(t28);
t38 = t22+t34;
et1 = (L.*g.*m.*t8.*1.0./t16.^3.*t26.*t35)./4.0-(L.*g.*m.*t8.*1.0./t16.^3.*t27.*t36)./4.0-(L.*g.*m.*t8.*1.0./t16.^3.*t29.*t35)./4.0+(L.*g.*m.*t8.*1.0./t16.^3.*t30.*t36)./4.0+(L.*g.*m.*t8.*t14.*t26.*t36.*(t10+(t6.*(t3-t4))./2.0))./2.0+(L.*g.*m.*t8.*t14.*t27.*t35.*(t10+(t6.*(t3-t4))./2.0))./2.0-(L.*g.*m.*t8.*t14.*t29.*t36.*(t10+(t6.*(t3-t4))./2.0))./2.0-(L.*g.*m.*t8.*t14.*t30.*t35.*(t10+(t6.*(t3-t4))./2.0))./2.0+(L.*g.*m.*t8.*t14.*t23.*t35.*t38)./2.0-(L.*g.*m.*t8.*t14.*t24.*t36.*t38)./2.0+(L.*g.*m.*t13.*t14.*t19.*t35.*theta0)./4.0;
et2 = L.*g.*m.*t13.*t14.*t20.*t36.*theta0.*(-1.0./4.0);
G = [(L.*g.*m.*t8.*t14.*t26.*t36)./2.0+(L.*g.*m.*t8.*t14.*t27.*t35)./2.0-(L.*g.*m.*t8.*t14.*t29.*t36)./2.0-(L.*g.*m.*t8.*t14.*t30.*t35)./2.0;L.*g.*m.*t12.*t14.*t19.*t35.*(-1.0./2.0)+(L.*g.*m.*t12.*t14.*t20.*t36)./2.0+(L.*g.*m.*t12.*t14.*t23.*t35)./2.0-(L.*g.*m.*t12.*t14.*t24.*t36)./2.0-(L.*g.*m.*t8.*1.0./t16.^3.*t26.*t36.*theta0)./2.0-(L.*g.*m.*t8.*1.0./t16.^3.*t27.*t35.*theta0)./2.0+(L.*g.*m.*t8.*1.0./t16.^3.*t29.*t36.*theta0)./2.0+(L.*g.*m.*t8.*1.0./t16.^3.*t30.*t35.*theta0)./2.0;et1+et2];
