function G = gravityVector(theta_r,theta0,theta1,m,g,L,D)
%GRAVITYVECTOR
%    G = GRAVITYVECTOR(THETA_R,THETA0,THETA1,M,G,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Feb-2022 14:46:24

t2 = theta0.^2;
t3 = theta1.^2;
t4 = theta0.*theta1.*2.0;
t5 = theta1.*theta_r.*2.0;
t6 = 1.0./theta1;
t8 = sqrt(pi);
t7 = 1.0./t3;
t9 = -t2;
t10 = t6.*theta0;
t11 = t6.*theta_r;
t12 = 1.0./t8;
t14 = sqrt(t6);
t17 = (t2.*t6)./2.0;
t18 = t2+t3+t4;
t23 = t6.*(t2-t5).*(-1.0./2.0);
t13 = t10+1.0;
t15 = -t11;
t16 = 1.0./t14;
t19 = t5+t9;
t20 = t12.*t14.*theta0;
t24 = t7.*(t2-t5).*(-1.0./2.0);
t25 = (t6.*t18)./2.0;
t26 = cos(t23);
t27 = sin(t23);
t32 = t17+t23;
t21 = fresnelc_approx(t20);
t22 = fresnels_approx(t20);
t28 = t12.*t13.*t16;
t31 = t15+t24;
t33 = cos(t32);
t34 = t23+t25;
t29 = fresnelc_approx(t28);
t30 = fresnels_approx(t28);
t35 = cos(t34);
mt1 = [(L.*g.*m.*t8.*t14.*t21.*t27)./2.0+(L.*g.*m.*t8.*t14.*t22.*t26)./2.0-(L.*g.*m.*t8.*t14.*t26.*t30)./2.0-(L.*g.*m.*t8.*t14.*t27.*t29)./2.0,L.*g.*m.*t6.*t33.*(-1.0./2.0)+(L.*g.*m.*t6.*t35)./2.0-(L.*g.*m.*t8.*1.0./t16.^3.*t21.*t27.*theta0)./2.0-(L.*g.*m.*t8.*1.0./t16.^3.*t22.*t26.*theta0)./2.0+(L.*g.*m.*t8.*1.0./t16.^3.*t26.*t30.*theta0)./2.0+(L.*g.*m.*t8.*1.0./t16.^3.*t27.*t29.*theta0)./2.0];
mt2 = [(L.*g.*m.*t7.*t33.*theta0)./4.0+(L.*g.*m.*t8.*t14.*t35.*((t7.*t16.^2.*t28)./2.0-t7.*t12.*t16.*theta0))./2.0+(L.*g.*m.*t8.*t14.*t21.*t27.*(t11+(t7.*(t2-t5))./2.0))./2.0+(L.*g.*m.*t8.*t14.*t22.*t26.*(t11+(t7.*(t2-t5))./2.0))./2.0-(L.*g.*m.*t8.*t14.*t26.*t30.*(t11+(t7.*(t2-t5))./2.0))./2.0-(L.*g.*m.*t8.*t14.*t27.*t29.*(t11+(t7.*(t2-t5))./2.0))./2.0+(L.*g.*m.*t7.*t8.*t16.*t21.*t26)./4.0-(L.*g.*m.*t7.*t8.*t16.*t22.*t27)./4.0-(L.*g.*m.*t7.*t8.*t16.*t26.*t29)./4.0+(L.*g.*m.*t7.*t8.*t16.*t27.*t30)./4.0];
G = reshape([mt1,mt2],3,1);
