function J = jacobianSoft(theta_r,theta0,theta1,s,d,L,D)
%JACOBIANSOFT
%    J = JACOBIANSOFT(THETA_R,THETA0,THETA1,S,D,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Feb-2022 15:09:17

t2 = s.*theta0;
t3 = s.*theta1;
t4 = s.^2;
t5 = theta0.^2;
t6 = theta1.^2;
t7 = theta1.*theta_r.*2.0;
t8 = 1.0./theta1;
t11 = sqrt(pi);
t15 = 1.0./sqrt(theta1);
t9 = 1.0./t6;
t10 = t3+theta0;
t12 = t2.*theta1.*2.0;
t13 = -t5;
t14 = 1.0./t11;
t16 = t15.^3;
t17 = t3.^2;
t18 = sqrt(t8);
t20 = (s.*t3)./2.0;
t22 = (t5.*t8)./2.0;
t37 = t8.*(t5-t7).*(-1.0./2.0);
t19 = t18.^3;
t21 = 1.0./t18;
t23 = t7+t13;
t24 = -t22;
t25 = t2+t20+theta_r;
t28 = s.*t14.*t15;
t29 = t14.*t15.*theta0;
t35 = t5+t12+t17;
t36 = t10.*t14.*t15;
t40 = cos(t37);
t41 = sin(t37);
t42 = (t10.*t14.*t16)./2.0;
t45 = t22+t37;
t26 = cos(t25);
t27 = sin(t25);
t30 = t24+theta_r;
t33 = fresnelc(t29);
t34 = fresnels(t29);
t38 = fresnelc(t36);
t39 = fresnels(t36);
t43 = -t42;
t44 = (t8.*t35)./2.0;
t31 = cos(t30);
t32 = sin(t30);
t46 = t28+t43;
t47 = t37+t44;
mt1 = [-D.*d.*t27+L.*t11.*t18.*t31.*t33-L.*t11.*t18.*t32.*t34-L.*t11.*t18.*t31.*t38+L.*t11.*t18.*t32.*t39,D.*d.*t26+L.*t11.*t18.*t31.*t34+L.*t11.*t18.*t32.*t33-L.*t11.*t18.*t31.*t39-L.*t11.*t18.*t32.*t38,-L.*t15.*t18.*t27+L.*t15.*t18.*sin(theta_r)-D.*d.*s.*t27-L.*t11.*t19.*t33.*t40.*theta0+L.*t11.*t19.*t34.*t41.*theta0+L.*t11.*t19.*t38.*t40.*theta0-L.*t11.*t19.*t39.*t41.*theta0,L.*t15.*t18.*t26-L.*t15.*t18.*cos(theta_r)+D.*d.*s.*t26-L.*t11.*t19.*t33.*t41.*theta0-L.*t11.*t19.*t34.*t40.*theta0+L.*t11.*t19.*t38.*t41.*theta0+L.*t11.*t19.*t39.*t40.*theta0];
mt2 = [D.*d.*t4.*t27.*(-1.0./2.0)-L.*t11.*t18.*t46.*sin(t47)-(L.*t16.*t18.*theta0.*sin(t45))./2.0-(L.*t9.*t11.*t21.*t33.*t41)./2.0-(L.*t9.*t11.*t21.*t34.*t40)./2.0+(L.*t9.*t11.*t21.*t38.*t41)./2.0+(L.*t9.*t11.*t21.*t39.*t40)./2.0+(L.*t5.*t9.*t11.*t18.*t33.*t40)./2.0-(L.*t5.*t9.*t11.*t18.*t34.*t41)./2.0-(L.*t5.*t9.*t11.*t18.*t38.*t40)./2.0+(L.*t5.*t9.*t11.*t18.*t39.*t41)./2.0];
mt3 = [(D.*d.*t4.*t26)./2.0+L.*t11.*t18.*t46.*cos(t47)+(L.*t16.*t18.*theta0.*cos(t45))./2.0+(L.*t9.*t11.*t21.*t33.*t40)./2.0-(L.*t9.*t11.*t21.*t34.*t41)./2.0-(L.*t9.*t11.*t21.*t38.*t40)./2.0+(L.*t9.*t11.*t21.*t39.*t41)./2.0+(L.*t5.*t9.*t11.*t18.*t33.*t41)./2.0+(L.*t5.*t9.*t11.*t18.*t34.*t40)./2.0-(L.*t5.*t9.*t11.*t18.*t38.*t41)./2.0-(L.*t5.*t9.*t11.*t18.*t39.*t40)./2.0];
J = reshape([mt1,mt2,mt3],2,3);
