function B = rotInertiaMatrix(theta_r,theta0,theta1,m,L,D)
%ROTINERTIAMATRIX
%    B = ROTINERTIAMATRIX(THETA_R,THETA0,THETA1,M,L,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    15-Feb-2022 17:35:43

t2 = theta0+theta1;
t3 = D.^2;
t4 = L.^2;
t5 = 1.0./theta1;
t6 = 1.0./sqrt(pi);
t7 = 1.0./sqrt(theta1);
t8 = (m.*t3)./2.4e+1;
t9 = (m.*t3)./4.8e+1;
t10 = t6.*t7.*theta0;
t13 = t2.*t6.*t7;
t11 = fresnelc_approx(t10);
t12 = fresnels_approx(t10);
t16 = fresnelc_approx(t13);
t17 = fresnels_approx(t13);
t14 = t11.^2;
t15 = t12.^2;
t18 = t16.^2;
t19 = t17.^2;
t28 = m.*t4.*t5.*t11.*t16.*pi;
t29 = m.*t4.*t5.*t12.*t17.*pi;
t20 = (m.*t4.*t5.*t14.*pi)./2.0;
t21 = (m.*t4.*t5.*t14.*pi)./4.0;
t22 = (m.*t4.*t5.*t15.*pi)./2.0;
t23 = (m.*t4.*t5.*t15.*pi)./4.0;
t24 = (m.*t4.*t5.*t18.*pi)./2.0;
t25 = (m.*t4.*t5.*t18.*pi)./4.0;
t26 = (m.*t4.*t5.*t19.*pi)./2.0;
t27 = (m.*t4.*t5.*t19.*pi)./4.0;
t30 = -t28;
t31 = -t29;
t32 = t28./2.0;
t33 = t29./2.0;
t34 = -t32;
t35 = -t33;
t36 = t8+t20+t22+t24+t26+t30+t31;
t37 = t9+t21+t23+t25+t27+t34+t35;
B = reshape([t36,t36,t37,t36,t36,t37,t37,t37,t28.*(-1.0./4.0)-t29./4.0+(m.*t3)./9.6e+1+(m.*t4.*t5.*t14.*pi)./8.0+(m.*t4.*t5.*t15.*pi)./8.0+(m.*t4.*t5.*t18.*pi)./8.0+(m.*t4.*t5.*t19.*pi)./8.0],[3,3]);
