function K = uniformElasticMatrix(k)
%UNIFORMELASTICMATRIX
%    K = UNIFORMELASTICMATRIX(K)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Feb-2022 04:24:14

t2 = k./2.0;
K = reshape([0.0,0.0,0.0,0.0,k,t2,0.0,t2,k./3.0],[3,3]);
