function ddx = f_fcn(x,dx,tau)
%
% function ddx = f_fcn(x,dx,tau)
%
% This function implements the dynamics leveraging the other functions
%  authomatically generated by generate_dynamics
%
global k beta

if nargin<3
    tau = 0;
end

if abs(x(1)) < 1e-5
    x(1) = 1e-5;
end

if abs(x(2)) < 1e-5
    x(2) = 1e-5;
end

B = B_fcn(x);
C = C_fcn(x,dx);
G = G_fcn(x);
ddx = B\(-C*dx -G - k*[1, 1/2; 1/2, 1/3]*x -beta*[1, 1/2; 1/2, 1/3]*dx + [1; 1/2]*tau);
%ddx = (-C*dx -G - k*[1, 1/2; 1/2, 1/3]*x -beta*[1, 1/2; 1/2, 1/3]*dx + [1; 1/2]*tau);