function A_lin = A_lin_fcn(m,g,L,k,beta)
%A_LIN_FCN
%    A_LIN = A_LIN_FCN(M,G,L,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    28-Mar-2020 22:23:17

t2 = 1.0./L.^2;
t3 = 1.0./m;
A_lin = reshape([0.0,0.0,-t2.*t3.*(k.*6.0-L.*g.*m.*(1.1e+1./1.0e+1)),0.0,0.0,0.0,t2.*t3.*(k.*1.2e+1-L.*g.*m.*(6.0./5.0)),0.0,1.0,0.0,beta.*t2.*t3.*-6.0,0.0,0.0,1.0,beta.*t2.*t3.*1.2e+1,0.0],[4,4]);
